// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelTracker.Data;

#nullable disable

namespace TravelTracker.Migrations
{
    [DbContext(typeof(TravelDbContext))]
    [Migration("20251214095750_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TravelTracker.Models.Accommodation", b =>
                {
                    b.Property<int>("AccommodationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccommodationId");

                    b.ToTable("Accommodations");

                    b.HasData(
                        new
                        {
                            AccommodationId = 1,
                            Name = "Готель"
                        },
                        new
                        {
                            AccommodationId = 2,
                            Name = "Хостел"
                        },
                        new
                        {
                            AccommodationId = 3,
                            Name = "Airbnb"
                        },
                        new
                        {
                            AccommodationId = 4,
                            Name = "У друзів"
                        });
                });

            modelBuilder.Entity("TravelTracker.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            Code = "UA",
                            Name = "Україна"
                        },
                        new
                        {
                            CountryId = 2,
                            Code = "PL",
                            Name = "Польща"
                        },
                        new
                        {
                            CountryId = 3,
                            Code = "IT",
                            Name = "Італія"
                        },
                        new
                        {
                            CountryId = 4,
                            Code = "FR",
                            Name = "Франція"
                        },
                        new
                        {
                            CountryId = 5,
                            Code = "DE",
                            Name = "Німеччина"
                        });
                });

            modelBuilder.Entity("TravelTracker.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccommodationId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ActualCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Budget")
                        .HasColumnType("TEXT");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TripTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TripId");

                    b.HasIndex("AccommodationId");

                    b.HasIndex("CountryId");

                    b.HasIndex("TripTypeId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("TravelTracker.Models.TripType", b =>
                {
                    b.Property<int>("TripTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TripTypeId");

                    b.ToTable("TripTypes");

                    b.HasData(
                        new
                        {
                            TripTypeId = 1,
                            Name = "Відпочинок"
                        },
                        new
                        {
                            TripTypeId = 2,
                            Name = "Робота"
                        },
                        new
                        {
                            TripTypeId = 3,
                            Name = "Екскурсія"
                        },
                        new
                        {
                            TripTypeId = 4,
                            Name = "Відрядження"
                        });
                });

            modelBuilder.Entity("TravelTracker.Models.Trip", b =>
                {
                    b.HasOne("TravelTracker.Models.Accommodation", "Accommodation")
                        .WithMany("Trips")
                        .HasForeignKey("AccommodationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelTracker.Models.Country", "Country")
                        .WithMany("Trips")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelTracker.Models.TripType", "TripType")
                        .WithMany("Trips")
                        .HasForeignKey("TripTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accommodation");

                    b.Navigation("Country");

                    b.Navigation("TripType");
                });

            modelBuilder.Entity("TravelTracker.Models.Accommodation", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("TravelTracker.Models.Country", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("TravelTracker.Models.TripType", b =>
                {
                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
